
Lmod is automatically replacing "cray-mpich/8.1.28" with "openmpi/5.0.0".

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import working_set
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run99_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

No PMIx server was reachable, but a PMI1/2 was detected.
If srun is being used to launch application,  128 singletons will be started.
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run106_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run106_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run109_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run113_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run117_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run122_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run124_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run125_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run126_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run131_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run146_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run148_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run155_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run156_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run157_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run160_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run164_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run167_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run170_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run170_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run174_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run176_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run177_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run178_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run179_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run185_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "batchRun.py", line 235, in <module>
    from batch_config_setup import *
  File "/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/batch_config_setup.py", line 116, in <module>
    os.makedirs(run_path)
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run187_128popevol_1x128'
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 128popevol_1x128
0 /global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: can't open 5
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run99_128popevol_1x128/gen_0/gen_0_cand_125.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run100_128popevol_1x128/gen_0/gen_0_cand_122.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run101_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run103_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run105_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run102_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run104_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run106_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run107_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run108_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run109_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run112_128popevol_1x128/gen_0/gen_0_cand_116.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run110_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run111_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run113_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run112_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run114_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run115_128popevol_1x128/gen_0/gen_0_cand_117.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run117_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run116_128popevol_1x128/gen_0/gen_0_cand_118.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run119_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run118_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run120_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run121_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run122_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run123_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run125_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run125_128popevol_1x128/gen_0/gen_0_cand_119.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run124_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run127_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run127_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run128_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run129_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run126_128popevol_1x128/gen_0/gen_0_cand_120.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run133_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run134_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run131_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run130_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run132_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run136_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run137_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run135_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run138_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run140_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run139_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run143_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run141_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run144_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run142_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run146_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run147_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run145_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run149_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run150_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run148_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run151_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run152_128popevol_1x128/gen_0/gen_0_cand_111.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run153_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run154_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run155_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run156_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run157_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run157_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run158_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run158_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run159_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run160_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run161_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run162_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run163_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run164_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run165_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run165_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run166_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run166_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run168_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run167_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run169_128popevol_1x128/gen_0/gen_0_cand_104.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run172_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run171_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run170_128popevol_1x128/gen_0/gen_0_cand_105.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run175_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run173_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run174_128popevol_1x128/gen_0/gen_0_cand_106.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run178_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run176_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run177_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run179_128popevol_1x128/gen_0/gen_0_cand_107.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run183_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run180_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run181_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run182_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run184_128popevol_1x128/gen_0/gen_0_cand_108.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run186_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run184_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run185_128popevol_1x128/gen_0/gen_0_cand_109.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run189_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run188_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run187_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
Traceback (most recent call last):
  File "/global/homes/a/adammwea/.conda/envs/2DSims/lib/python3.9/site-packages/netpyne/batch/utils.py", line 310, in runJob
    with open(simDataPath + '.run', 'w') as outf, open(simDataPath + '.err', 'w') as errf:
FileNotFoundError: [Errno 2] No such file or directory: '/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run190_128popevol_1x128/gen_0/gen_0_cand_110.run'

/global/homes/a/adammwea/.conda/envs/2DSims/bin/nrniv: PyObject method call failed:
 near line 0
 objref hoc_obj_[2]
                   ^
        ParallelContext[4].working()
slurmstepd: error: *** STEP 24760269.0 ON nid004209 CANCELLED AT 2024-04-25T06:49:39 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 24760269 ON nid004209 CANCELLED AT 2024-04-25T06:49:39 DUE TO TIME LIMIT ***
